server:
  version: '2.0'
  hostname: weblogin.asu.edu
  port: 443
  path: /cas
  verify: 0
  cert: ''
gateway:
  check_frequency: -1
  paths:
    id: request_path
    pages: "<front>\r\n"
    negate: false
forced_login:
  enabled: true
  paths:
    id: request_path
    pages: "/admin/*\r\n/user\r\n/node/add\r\nnode/*/edit"
    negate: false
logout:
  logout_destination: ''
  enable_single_logout: true
  cas_logout: true
  single_logout_session_lifetime: 25
proxy:
  initialize: false
  can_be_proxied: false
  proxy_chains: ''
user_accounts:
  prevent_normal_login: true
  auto_register: true
  email_assignment_strategy: 0
  email_hostname: asu.edu
  email_attribute: ''
  auto_assigned_roles:
    - cas_user
  restrict_password_management: false
  restrict_email_management: false
advanced:
  debug_log: false
  connection_timeout: 10
login_link_enabled: false
login_link_label: 'CAS Login'
_core:
  default_config_hash: 8DaBBGvjnTAKJrdg2aY2FHId9Qt4D2Yek7gozPUx6v8
